# Introduction to Pandas Lab

Complete the following set of exercises to solidify your knowledge of Pandas fundamentals.

### 1. Import Numpy and Pandas and alias them to `np` and `pd` respectively.

In [1]:
import pandas as pd
import numpy as np

### 2. Create a Pandas Series containing the elements of the list below.

In [3]:
lst = [5.7, 75.2, 74.4, 84.0, 66.5, 66.3, 55.8, 75.7, 29.1, 43.7]

In [7]:
# your code here
series_lst = pd.Series(lst)
print(series_lst)

0     5.7
1    75.2
2    74.4
3    84.0
4    66.5
5    66.3
6    55.8
7    75.7
8    29.1
9    43.7
dtype: float64

In [8]:
# Alternatively
series_lst

0     5.7
1    75.2
2    74.4
3    84.0
4    66.5
5    66.3
6    55.8
7    75.7
8    29.1
9    43.7
dtype: float64

### 3. Use indexing to return the third value in the Series above.

*Hint: Remember that indexing begins at 0.*

In [10]:
# your code here
series_lst[2]

np.float64(74.4)

### 4. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [35]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [36]:
# your code here

df = pd.DataFrame(b)
print(df)

      0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7

In [37]:
# Alternatively
df

      0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7

### 5. Rename the data frame columns based on the names in the list below.

In [7]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [38]:
# your code here
df = pd.DataFrame(b)
b_names = ["Score_1", "Score_2", "Score_3", "Score_4", "Score_5"]
df.columns = b_names
print(df)

   Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

In [39]:
# Alternatively
df

   Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

### 6. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [40]:
# your code here
subset = df[["Score_1", "Score_3", "Score_5"]]

print(subset)

   Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

In [41]:
subset

   Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 7. From the original data frame, calculate the average Score_3 value.

In [43]:
# your code here
Avg_Score_3 = df["Score_3"].mean()
print(Avg_Score_3)

56.95000000000001

In [29]:
Avg_Score_3

np.float64(56.95000000000001)

### 8. From the original data frame, calculate the maximum Score_4 value.

In [44]:
# your code here
max_Score_4 = df["Score_4"].max()
print(max_Score_4)

88.8

In [45]:
max_Score_4

np.float64(88.8)

### 9. From the original data frame, calculate the median Score 2 value.

In [46]:
# your code here
median_Score_2 = df["Score_2"].median()
print(median_Score_2)

40.75

### 10. Create a Pandas DataFrame from the dictionary of product orders below.

In [50]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [51]:
# your code here
df = pd.DataFrame(orders)
df

                          Description  Quantity  UnitPrice  Revenue
0              LUNCH BAG APPLE DESIGN         1       1.65     1.65
1  SET OF 60 VINTAGE LEAF CAKE CASES         24       0.55    13.20
2         RIBBON REEL STRIPES DESIGN          1       1.65     1.65
3   WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880       0.18   518.40
4    PLAYING CARDS JUBILEE UNION JACK         2       1.25     2.50
5                      POPCORN HOLDER         7       0.85     5.95
6      BOX OF VINTAGE ALPHABET BLOCKS         1      11.95    11.95
7                       PARTY BUNTING         4       4.95    19.80
8            JAZZ HEARTS ADDRESS BOOK        10       0.19     1.90
9       SET OF 4 SANTA PLACE SETTINGS        48       1.25    60.00

### 11. Calculate the total quantity ordered and revenue generated from these orders.

In [52]:
# your code here
total_quantity = df["Quantity"].sum()
total_revenue = df["Revenue"].sum()

print(total_quantity)
print(total_revenue)

2978
637.0

In [ ]:
# Alternatively
df[["Quantity", "Revenue"]].sum()

Quantity    2978.0
Revenue      637.0
dtype: float64

### 12. Obtain the prices of the most expensive and least expensive items ordered and print the difference.

In [55]:
# your code here
df["UnitPrice"].max() - df["UnitPrice"].min()

np.float64(11.77)

In [56]:
# Alternative solution
max_price = df["UnitPrice"].max()
min_price = df["UnitPrice"].min()

price_difference = max_price - min_price

print("Most expensive:", max_price)
print("Least expensive:", min_price)
print("Difference:", price_difference)

Most expensive: 11.95
Least expensive: 0.18
Difference: 11.77

## Let's load another dataset for more exercisesº

In [105]:
# Run this code:
admissions = pd.read_csv('../Admission_Predict.csv')

In [106]:
admissions.shape

(385, 9)

In [ ]:
#admissions = pd.read_csv(r"C:\Users\34673\OneDrive\IRONHACK BOOTCAMP1\EXERCISES\WEEK2\DAY_2\lab-pandas-en\Admission_Predict.csv")

In [ ]:
#admissions.shape

(385, 9)

Let's evaluate the dataset by looking at the `head` function.

In [107]:
# your code here
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90

### 1 - Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [108]:
# your code here
admissions.isnull().values.any()

np.False_

In [109]:
admissions

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
380,381,324,110,3,3.5,3.5,9.04,1,0.82
381,382,325,107,3,3.0,3.5,9.11,1,0.84
382,383,330,116,4,5.0,4.5,9.45,1,0.91
383,384,312,103,3,3.5,4.0,8.78,0,0.67
384,385,333,117,4,5.0,4.0,9.66,1,0.95

In [110]:
# Alternative solution
admissions.isnull().any().any()

np.False_

In [111]:
admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         385 non-null    int64
 1   GRE Score          385 non-null    int64
 2   TOEFL Score        385 non-null    int64
 3   University Rating  385 non-null    int64
 4   SOP                385 non-null    float64
 5   LOR                385 non-null    float64
 6   CGPA               385 non-null    float64
 7   Research           385 non-null    int64
 8   Chance of Admit    385 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 27.2 KB

###  2 -  Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [112]:
# your code here
admissions.set_index("Serial No.", drop=False, inplace=True)
admissions

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,316,104,3,3.0,3.5,8.00,1,0.72
3,3,322,110,3,3.5,2.5,8.67,1,0.80
4,4,314,103,2,2.0,3.0,8.21,0,0.65
5,5,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
381,381,324,110,3,3.5,3.5,9.04,1,0.82
382,382,325,107,3,3.0,3.5,9.11,1,0.84
383,383,330,116,4,5.0,4.5,9.45,1,0.91
384,384,312,103,3,3.5,4.0,8.78,0,0.67
385,385,333,117,4,5.0,4.0,9.66,1,0.95

In [113]:
# Alternative solution
admissions = admissions.set_index("Serial No.", drop=False)
admissions

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,316,104,3,3.0,3.5,8.00,1,0.72
3,3,322,110,3,3.5,2.5,8.67,1,0.80
4,4,314,103,2,2.0,3.0,8.21,0,0.65
5,5,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
381,381,324,110,3,3.5,3.5,9.04,1,0.82
382,382,325,107,3,3.0,3.5,9.11,1,0.84
383,383,330,116,4,5.0,4.5,9.45,1,0.91
384,384,312,103,3,3.5,4.0,8.78,0,0.67
385,385,333,117,4,5.0,4.0,9.66,1,0.95

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

### 3 - In this part of the lab, we would like to test complex conditions on the entire data set at once. Let's start by finding the number of rows where the CGPA is greater than 9 and the student has performed an investigation.

In [114]:
# your code here
admissions[["GRE Score", "CGPA"]].duplicated().sum()

np.int64(0)

In [115]:
count = admissions[(admissions["CGPA"] > 9) & (admissions["Research"] == 1)].shape[0]
count

101

### 4 - Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [116]:
# your code here
# Firstly, filter the DataFrame based on the conditions and then count the number of rows in the filtered DataFrame.
filtered = admissions[(admissions["CGPA"] > 9) & (admissions["SOP"] < 3.5)]

# Calculating the 'mean' of the 'Chance of Admit' column for the filtered DataFrame
mean_chance_of_admit = filtered["Chance of Admit "].mean()
mean_chance_of_admit

np.float64(0.8019999999999999)

In [117]:
# Alternative solution
mean_chance = admissions[(admissions["CGPA"] > 9) & (admissions["SOP"] < 3.5)]["Chance of Admit "].mean()
mean_chance

np.float64(0.8019999999999999)